language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script: - pytest --with-coverage --cover-package=app

after_success:
  coveralls